version: '3.9'

services:
    backend:
        container_name: backend
        restart: always
        build:
            context: ./BACK/
            target: backend-dev
        ports:
            - 5000:5000
        environment:
            JWT_SECRET: ${JWT_SECRET}
            DEFAULT_LOGIN: ${DEFAULT_LOGIN}
            DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
    frontend:
        container_name: frontend
        restart: always
        build:
            context: ./frontend/
            target: frontend-dev
        ports:
            - 3000:3000